const yohohamaMembers = [
	{ team: "日本研究所長", name: "Oh Chang Ho" },
	{ team: "PA Team", name: "Shin Ha Lim" },
	{ team: "PA Team", name: "Iida Haruhisa" },
	{ team: "PA Team", name: "Kim Ji Gang" },
	{ team: "PA Team", name: "Sato Kazutaka" },
	{ team: "PA Team", name: "Lee Min Sook" },
	{ team: "PA Team", name: "Baek Soo Jung" },
	{ team: "PA Team", name: "Shimizu Kouki" },
	{ team: "PA Team", name: "Tamai Kazuhiko" },
	{ team: "PA Team", name: "Yang Daegyu" },
	{ team: "PA Team", name: "Lee Go Eun" },
	{ team: "PA Team", name: "Tsukamoto Mamika" },
	{ team: "PA Team", name: "Kitagawa Hirohisa" },
	{ team: "HR Team", name: "Hara Kazuhiko" },
	{ team: "HR Team", name: "Yoon Sung June" },
	{ team: "HR Team", name: "Takano Mai" },
	{ team: "HR Team", name: "Hirai Toko" },
	{ team: "HR Team", name: "Murase Yu" },
	{ team: "HR Team", name: "Sato Takuya" },
	{ team: "Technology Center Japan", name: "Yoshida Yasukazu" },
	{ team: "Technology Center Japan", name: "Shin Ji Sik" },
	{ team: "Technology Center Japan", name: "Kim Yeji" },
	{ team: "Technology Center Japan", name: "Chang Byunghoon" },
	{ team: "Technology Center Japan", name: "Cho Seungjin" },
	{ team: "Technology Center Japan", name: "Lee Seungwoo" },
	{ team: "Display 研究室", name: "Noh Seonghee" },
	{ team: "Display 研究室", name: "Satoh Ryuichi" },
	{ team: "Display 研究室", name: "Ohata Hiroshi" },
	{ team: "Display 研究室", name: "Morimoto Kazunori" },
	{ team: "Display 研究室", name: "Yasuhiro Takahashi" },
	{ team: "Display 研究室", name: "Takimoto Hiroto" },
	{ team: "Display 研究室", name: "Kato Taichi" },
	{ team: "Display 研究室", name: "Hirano Takashi" },
	{ team: "Display 研究室", name: "Tokunaga Shoichi" },
	{ team: "Display 研究室", name: "Matsuo Kyohei" },
	{ team: "化学 研究室", name: "Ko Jung Min" },
	{ team: "化学 研究室", name: "Kang Jinnie" },
	{ team: "化学 研究室", name: "Takeda Tadashi" },
	{ team: "化学 研究室", name: "Kizaki Shingo" },
	{ team: "化学 研究室", name: "Imaizumi Shin" },
	{ team: "化学 研究室", name: "Oishi Kengo" },
	{ team: "化学 研究室", name: "Irii Yuta" },
	{ team: "化学 研究室", name: "Shin Sun Ah" },
	{ team: "化学 研究室", name: "Habaki Shin" },
	{ team: "化学 研究室", name: "Kang Dongho" },
	{ team: "AQUA TDR", name: "Mishina Noriyuki" },
	{ team: "AQUA TDR", name: "Hama Takeshi" },
	{ team: "AQUA TDR", name: "Seo Hee Sook" },
	{ team: "AQUA TDR", name: "Suzuki Takayuki" },
	{ team: "AQUA TDR", name: "Park Yohan" },
	{ team: "AQUA TDR", name: "Hwang Byungchan" },
	{ team: "先端研究1室", name: "Kumei Masami" },
	{ team: "先端研究1室", name: "Kurabayashi Yasuo" },
	{ team: "先端研究1室", name: "Kang Sungmin" },
	{ team: "先端研究1室", name: "Watanabe Tatsuya" },
	{ team: "先端研究1室", name: "Inoue Yuuki" },
	{ team: "先端研究1室", name: "Nakasugi Shigemasa" },
	{ team: "先端研究1室", name: "Ye Jae Hun" },
	{ team: "先端研究1室", name: "Natsume Shuhei" },
	{ team: "先端研究1室", name: "Kobayashi Tsubasa" },
	{ team: "先端研究1室", name: "Takeuchi Yuu" },
	{ team: "先端研究1室", name: "Matsui Masafuyu" },
	{ team: "先端研究1室", name: "Sako Masami" },
	{ team: "先端研究1室", name: "Morishita Yuto" },
	{ team: "先端研究1室", name: "Okushima Shun" },
	{ team: "先端研究1室", name: "Yang Yue" },
	{ team: "先端研究1室", name: "Ishizaki Hiroki" },
	{ team: "先端研究2Team", name: "Hiraki Katsuyoshi" },
	{ team: "先端研究2Team", name: "Sato Yohei" },
	{ team: "先端研究2Team", name: "Watanabe Kazuki" },
	{ team: "先端研究2Team", name: "Shohji Iwao" },
	{ team: "先端研究2Team", name: "Sampei Tomohiro" },
	{ team: "先端研究2Team", name: "Kim Min Soo" },
	{ team: "先端研究3Team", name: "Takasugi Shinji" },
	{ team: "先端研究3Team", name: "Lee Taewoo" },
	{ team: "先端研究3Team", name: "Ichikawa Tsutomu" },
	{ team: "先端研究3Team", name: "Miyokawa Tomonori" },
	{ team: "先端研究3Team", name: "Ji Hyun Jong" },
	{ team: "先端研究3Team", name: "Nakao Yoshihiro" },
	{ team: "Energy Solution 研究室", name: "Matsubara Keiko" },
	{ team: "Energy Solution 研究室", name: "Takeuchi Takashi" },
	{ team: "Energy Solution 研究室", name: "Nitta Yoshiaki" },
	{ team: "Energy Solution 研究室", name: "Takamuku Akira" },
	{ team: "Energy Solution 研究室", name: "Chihara Kuniko" },
	{ team: "Energy Solution 研究室", name: "Sakamoto Shuhei" },
	{ team: "Energy Solution 研究室", name: "Ishida Maki" },
	{ team: "Energy Solution 研究室", name: "Song Sunyoung" },
	{ team: "Energy Solution 研究室", name: "Narimatsu Eiichiro" },
	{ team: "Energy Solution 研究室", name: "Tsuchiya Hajime" },
	{ team: "Energy Solution 研究室", name: "Ikenomoto Shun" },
	{ team: "Energy Solution 研究室", name: "Song Subin" },
	{ team: "Components Team", name: "Sammyo Masahiro" },
	{ team: "Components Team", name: "Kato Takuma" },
	{ team: "Components Team", name: "Yamazaki Shoichi" },
	{ team: "Components Team", name: "Kodaira Hiroshi" },
	{ team: "Components Team", name: "Sakai Takaaki" },
	{ team: "Components Team", name: "Takano Yohei" },
	{ team: "MS Team", name: "Dewa Yoshiharu" },
	{ team: "MS Team", name: "Matsumoto Takashi " },
	{ team: "MS Team", name: "Takenaka Ryuji" },
	{ team: "MS Team", name: "Lee Jun Yee" },
	{ team: "MS Team", name: "Koizumi Haruo" },
	{ team: "MS Team", name: "Song Eunji" },
	{ team: "MS Team", name: "Arai Koji" },
	{ team: "MS Team", name: "Mikuriya Yojiro" },
	{ team: "MS Team", name: "Shinohara Masahiko" },
	{ team: "MS Team", name: "Sudo Satoshi" },
	{ team: "MS Team", name: "Han Chang Sam" },
	{ team: "MS Team", name: "Jung Ilkwon" },
	{ team: "MS Team", name: "Kim InKyun" },

];

const kyotoMembers = [
	{ team: "HS&ES Team", name: "Asami Tadashi" },
	{ team: "HS&ES Team", name: "Inoue Hiroyuki" },
	{ team: "HS&ES Team", name: "Kim Hyeongsu" },
	{ team: "HS&ES Team", name: "Inoue Hiroyuki" },
	{ team: "HS&ES Team", name: "Mori Kazushi" },
	{ team: "HS&ES Team", name: "Ju Minchul" },
	{ team: "HS&ES Team", name: "Furubayashi Mitsuyuki" },
	{ team: "HS&ES Team", name: "Nishioka Yoshiyuki" },
	{ team: "HS&ES Team", name: "Sato Sakiko" },
	{ team: "HS&ES Team", name: "Shimono Masahito" },
	{ team: "HS&ES Team", name: "Otomo Hiroshi" },
	{ team: "HS&ES Team", name: "Ishikawa Sakae" },
	{ team: "HS&ES Team", name: "Nishigaki Kenichi" },
	{ team: "HS&ES Team", name: "Otsubo Yuta" },
	{ team: "HS&ES Team", name: "Tomigashi Yoshio" },
	{ team: "HS&ES Team", name: "Fujioka Hirotoshi" },
	{ team: "HS&ES Team", name: "Takemura Nozomu" },
	{ team: "HS&ES Team", name: "Arai Izumi"	}
];
